services:
  marker:
    build:
      context: .
      dockerfile: server/Dockerfile
    platform: linux/amd64
    ports:
      - 8003:8000
    environment:
      - LOG_LEVEL=DEBUG
      - API_KEY=key
    volumes:
      - models:/root/.cache/datalab/models
    develop:
      watch:
        - action: sync+restart
          path: ./server
          target: /server
        - action: rebuild
          path: ./server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

volumes:
  models:
